# Generated by Django 5.2.17 on 2026-08-18 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("engine", "0106_add_interval_annotations"),
    ]

    operations = [
        migrations.CreateModel(
            name="RasterSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("source_path", models.CharField(max_length=1024)),
                (
                    "crs_wkt",
                    models.TextField(
                        help_text="Well-known text representation of the raster's CRS"
                    ),
                ),
                ("transform_a", models.FloatField()),
                ("transform_b", models.FloatField()),
                ("transform_c", models.FloatField()),
                ("transform_d", models.FloatField()),
                ("transform_e", models.FloatField()),
                ("transform_f", models.FloatField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("band_count", models.PositiveSmallIntegerField()),
                ("dtype", models.CharField(max_length=32)),
                ("nodata_value", models.FloatField(blank=True, null=True)),
                ("tile_size", models.PositiveIntegerField()),
                ("overlap", models.PositiveIntegerField()),
                ("was_reencoded_as_cog", models.BooleanField(default=False)),
                (
                    "display_bands",
                    models.JSONField(
                        default=list,
                        help_text="1-indexed band numbers used for the browser-facing PNG tiles",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raster_sources",
                        to="engine.task",
                    ),
                ),
            ],
            options={
                "default_related_name": "raster_sources",
            },
        ),
        migrations.CreateModel(
            name="RasterTaskConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                ("tile_size", models.PositiveIntegerField()),
                ("overlap", models.PositiveIntegerField()),
                ("reencode_as_cog", models.BooleanField(default=True)),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raster_config",
                        to="engine.task",
                    ),
                ),
            ],
            options={
                "default_related_name": "raster_config",
            },
        ),
        migrations.CreateModel(
            name="RasterTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("frame", models.PositiveIntegerField()),
                ("row", models.PositiveIntegerField()),
                ("col", models.PositiveIntegerField()),
                ("col_off", models.PositiveIntegerField()),
                ("row_off", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("pad_right", models.PositiveIntegerField(default=0)),
                ("pad_bottom", models.PositiveIntegerField(default=0)),
                (
                    "raster_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="geospatial.rastersource",
                    ),
                ),
            ],
            options={
                "ordering": ["frame"],
                "default_related_name": "tiles",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("raster_source", "frame"), name="unique_frame_per_raster_source"
                    )
                ],
            },
        ),
    ]
